# Generated by Django 4.1.7 on 2023-05-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='prices',
            new_name='price_name',
        ),
        migrations.AlterField(
            model_name='course_title',
            name='title_name',
            field=models.TextField(max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(unique=True),
        ),
    ]
