# Generated by Django 4.1.7 on 2023-05-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_prices_price_price_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title_pic',
            name='title_pic',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
